#!/bin/sh

set -e
set -x

export PROJECT_ROOT=/srv/project
export LOG_ROOT=/data/log

# Make sure log dir exists.
mkdir -p ${LOG_ROOT}

# Start all processes with Supervisord.
supervisord -c ./targets/run/supervisord.conf -n
